### ISSUE TITLE
load_from_prod returning errors

### ISSUE THREAD

**Issue by jessimb** [catapult-project/catapult#3024]
I am trying to use load_from_prod with a local version of catapult running and get 
"Could not fetch https://chromeperf.appspot.com/dump_graph_json?sheriff=Chromium%20Perf%20Sheriff&num_alerts=10&num_points=100"

When I go to the above link, I get a 200 OK, so I'm not sure why load_from_prod isn't working.

Along the same lines, we've discovered that when you are signed into the dashboard, dump_graph_json gives a 200, but signed out gives a 500. We're not sure if being signed in should be a requirement for dump_graph_json or even why it doesn't work for signed out users.

@eakuefner @anniesullie

**Comment by anniesullie** [comment]
The problem is the way the data is indexed. If you go to go/chromeperf-logs and type `path:/dump_graph_json` into the search you'll see the error:

```
suspended generator _run_to_list(query.py:995) raised NeedIndexError(no matching index found. recommended index is: (/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py:468)
- kind: Row
  properties:
  - name: internal_only
  - name: revision
    direction: desc

The suggested index for this query is:
- kind: Row
  properties:
  - name: internal_only
  - name: parent_test
  - name: revision
    direction: desc)
```

We used to have indexes for both signed out and signed in users for the queries load_graph_from_prod does. But that added an extra 12TB of indexes. It broke when I removed them.

I think the right thing to do is:
1. Only support externally available data from `load_graph_from_prod`, since there's no simple way to authenticate requests.
2. Fix the query in `dump_graph_json` not to depend on `internal_only` property.
