### ISSUE TITLE
Dashboard - Do we need both indexes for internal_only?

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4440]
Do we need both of these indexes? Isn't it sufficient to declare one composite index with internal_only, and just not use that field when doing privileged queries?

@anniesullie @eakuefner

**Comment by anniesullie** [comment]
I think the composite one is the only one that is needed. But I don't know how to test.

**Comment by simonhatch** [comment]
I meant that index.yaml typically has 2 composite indexes for each query, with and without internal_only, but not clear if we need the one that doesn't have internal_only

**Comment by anniesullie** [comment]
Ah, I see. At least when I tried it last, the queries that didn't check internal_only would fail without their own index. I may have been holding it wrong?

**Comment by simonhatch** [comment]
Ahh ok, was wondering if they could somehow be collapsed instead of having 2 of each. Sounds like maybe they can't.

**Comment by simonhatch** [comment]
Had a random thought, could maybe just turn the datastore PreCallHook to a PostCallHook and filter out the internal_only as a post step, that'd let us remove this double index thing.

**Comment by benshayden** [comment]
I would be concerned that filtering by internal_only post-hoc rather than in the query would artificially limit the number of results. The fetch limit is applied after the query filters but before the post-hoc filtering. You could run the query in a loop until you find enough matching entities, but that could significantly impact request latency.

Alternatively, you could restructure the indexes to take advantage of zigzag merge. This should significantly reduce the storage size of the indexes, and only increase query latency slightly.
```
- kind: TestMetadata
  properties:
  - name: master_name
  - name: bot_name
  - name: suite_name
  - name: test_part1_name
  - name: test_part2_name
  - name: test_part3_name
  - name: test_part4_name
  - name: test_part5_name
  - name: key
- kind: TestMetadata
  properties:
  - name: internal_only
  - name: key
```
I'm actually not sure about that `name: key` part. I just noticed that list_tests orders by key. I'm also not sure if that actually has any effect. If the `name: key` part is not necessary, then you don't need to explicitly define an index over just internal_only because the datastore automatically provides single-property indexes as a built-in.

Alternatively2, you could use an inequality filter for internal_only and remove the index that doesn't include internal_only altogether. This would halve the index storage cost. The only downside is that queries cannot contain more than one inequality filter, so you wouldn't be able to use this trick for any other properties.
```
query = query.filter(graph_data.TestMetadata.internal_only != None)
```
That would match both internal_only=True and internal_only=False.

Alternatively3, we could hold off refactoring the TestMetadata indexes until we can discuss how V2SPA's descriptor concept might affect the shape of that Model.
